<?php
/**
 * Title: Case study: full story layout
 * Slug: hpv/case-study-body
 * Categories: hpv-pages
 * Description: Hero image, snapshot, story, results, lessons, testimonial and call to action.
 * Post Types: case_study
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:hpv/project {"name":"Imperial Kitchens","src":"projects/imperial-kitchens-1","ratio":"wide","tone":2,"alt":"The new Imperial Kitchens website on desktop","eager":true} /--></div>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"story"} -->
<section class="wp-block-group section" id="story"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:hpv/case-snapshot {"className":"col-3"} /-->
<!-- wp:group {"className":"col-8 start-5"} -->
<div class="wp-block-group col-8 start-5"><!-- wp:hpv/case-result /-->
<!-- wp:group {"className":"story mt-12"} -->
<div class="wp-block-group story mt-12"><!-- wp:heading -->
<h2 class="wp-block-heading">The challenge</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tbd"} -->
<p class="tbd">[80–120 words. What wasn’t working, in the owner’s terms. e.g. “Work came almost entirely from referrals. The website looked fine, but it didn’t bring in calls, and the owner had no idea which marketing spend paid back.”]</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"word-note"} -->
<p class="word-note">80–120 words</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">The business situation</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tbd"} -->
<p class="tbd">[100–150 words. Market, competition, goals and constraints: budget, season, team size, the premium segment they want more of.]</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"word-note"} -->
<p class="word-note">100–150 words</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">The strategy</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tbd"} -->
<p class="tbd">[150–250 words. The key insight and the decisions made — including what we chose not to do. e.g. no paid ads until the site converted; focus on two service lines and three cities.]</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"word-note"} -->
<p class="word-note">150–250 words</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">What we built</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tbd"} -->
<p class="tbd">[150–250 words. Website, SEO, campaigns, tracking. 2–4 images or before/after.]</p>
<!-- /wp:paragraph -->
<!-- wp:group {"className":"grid grid--rows mt-4"} -->
<div class="wp-block-group grid grid--rows mt-4"><!-- wp:group {"className":"col-6"} -->
<div class="wp-block-group col-6"><!-- wp:hpv/photo {"src":"projects/imperial-kitchens-before","ratio":"land","alt":"The Imperial Kitchens website before the project","note":"Before|Screenshot"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-6"} -->
<div class="wp-block-group col-6"><!-- wp:hpv/project {"name":"Imperial Kitchens","src":"projects/imperial-kitchens-3","ratio":"land","tone":4,"alt":"The Imperial Kitchens website after the project"} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"gallery"} -->
<section class="wp-block-group section section--flush-top" id="gallery"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"work"} -->
<div class="wp-block-group work"><!-- wp:group {"tagName":"article","className":"work-item work-item--lg"} -->
<article class="wp-block-group work-item work-item--lg"><!-- wp:hpv/project {"name":"Imperial Kitchens","src":"projects/imperial-kitchens-4","ratio":"wide","tone":5,"alt":"Imperial Kitchens service page"} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name">Service pages</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat">One page per remodeling service</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item work-item--md"} -->
<article class="wp-block-group work-item work-item--md"><!-- wp:hpv/project {"name":"Imperial Kitchens","src":"projects/imperial-kitchens-5","ratio":"portrait","tone":6,"alt":"Imperial Kitchens website on a phone"} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name">Mobile first</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat">Tap-to-call on every page</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-accent","anchor":"results"} -->
<section class="wp-block-group section bg-accent" id="results"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label">Outcome</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">What changed</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"stats"} -->
<div class="wp-block-group stats"><!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[+X%]</span></span><span class="stat__ctx">organic calls, <span class="tbd">[timeframe]</span></span><span class="stat__src">Source: <span class="tbd">[call tracking]</span></span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[X]</span></span><span class="stat__ctx">form requests per month</span><span class="stat__src">Source: <span class="tbd">[GA4]</span></span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[Top 3]</span></span><span class="stat__ctx">map pack for <span class="tbd">[primary search]</span></span><span class="stat__src">Source: <span class="tbd">[rank tracker, date]</span></span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph {"className":"body mt-6 tbd"} -->
<p class="body mt-6 tbd">[~60 words putting the numbers in context. If a number can’t be shared, describe the outcome qualitatively and say why (“client figures are confidential”).]</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"lessons"} -->
<section class="wp-block-group section" id="lessons"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label">Lessons</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">What any owner can take from this</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"blocks blocks--3"} -->
<div class="wp-block-group blocks blocks--3"><!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">01</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tbd"} -->
<p class="tbd">[Takeaway one]</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">02</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tbd"} -->
<p class="tbd">[Takeaway two]</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">03</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tbd"} -->
<p class="tbd">[Takeaway three]</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"testimonial"} -->
<section class="wp-block-group section bg-paper" id="testimonial"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"testimonial"} -->
<div class="wp-block-group testimonial"><!-- wp:quote -->
<blockquote class="wp-block-quote "><!-- wp:paragraph -->
<p><span class="tbd">[Named quote, 1–3 sentences, with written permission.]</span></p>
<!-- /wp:paragraph --></blockquote>
<!-- /wp:quote -->
<!-- wp:paragraph {"className":"testimonial__by"} -->
<p class="testimonial__by"><span class="tbd">[Name]</span>, <span class="tbd">[Role]</span>, <span class="tbd">[Imperial Kitchens]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"final-cta"} -->
<section class="wp-block-group section" id="final-cta"><!-- wp:group {"className":"wrap cta-band"} -->
<div class="wp-block-group wrap cta-band"><!-- wp:group {"className":"stack"} -->
<div class="wp-block-group stack"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Facing a similar challenge?</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>See how <a class="link" href="<?php echo esc_url( home_url( '/services/website-design-development/' ) ); ?>">website design for Florida service businesses</a> and <a class="link" href="<?php echo esc_url( home_url( '/services/local-seo/' ) ); ?>">local SEO in Fort Myers</a> work together.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph {"className":"cta-band__action"} -->
<p class="cta-band__action"><a class="btn" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
