<?php
/**
 * Title: Page: Page not found
 * Slug: hpv/page-404
 * Categories: hpv-pages
 * Description: This page doesn't exist.
 * Post Types: page
 * Inserter: no
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner"} -->
<section class="wp-block-group hero hero--inner"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"hero__text col-8"} -->
<div class="wp-block-group hero__text col-8"><!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Error 404</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display">This page took a <span class="scribble">different route</span>.</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">The link may be old, or the page has moved. Here are the places most owners are looking for.</p>
<!-- /wp:paragraph -->
<!-- wp:list {"className":"mobile-menu__list mobile-menu__list--inline mt-4"} -->
<ul class="wp-block-list mobile-menu__list mobile-menu__list--inline mt-4"><!-- wp:list-item -->
<li><a href="<?php echo esc_url( home_url( '/services/' ) ); ?>">Services <span aria-hidden="true">→</span></a></li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Case Studies <span aria-hidden="true">→</span></a></li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li><a href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
