<?php
/**
 * Title: Page: Book a Strategy Call
 * Slug: hpv/page-strategy-call
 * Categories: hpv-pages
 * Description: A free 30-minute call to find where your growth is stuck. No pitch, no obligation.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner","anchor":"hero"} -->
<section class="wp-block-group hero hero--inner" id="hero"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:paragraph {"className":"sticker"} -->
<p class="sticker">30 min · Free · No pitch</p>
<!-- /wp:paragraph -->
<!-- wp:group {"className":"hero__text col-8"} -->
<div class="wp-block-group hero__text col-8"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Strategy Call · 30 minutes · Free</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display">Book a <span class="scribble">strategy call</span></h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">30 minutes with Áron to look at your business, your goals and where growth is getting stuck. No pitch deck, no obligation.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"call"} -->
<section class="wp-block-group section section--flush-top" id="call"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-7"} -->
<div class="wp-block-group col-7"><!-- wp:hpv/strategy-call-form /--></div>
<!-- /wp:group -->
<!-- wp:group {"tagName":"aside","className":"col-4 start-9 side-panel"} -->
<aside class="wp-block-group col-4 start-9 side-panel"><!-- wp:hpv/photo {"src":"people/aron-headshot","ratio":"portrait","alt":"Áron Ritók-Filip","note":"Headshot · 4:5|Shoot pending"} /-->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Based in Southwest Florida</p>
<!-- /wp:paragraph -->
<!-- wp:hpv/contact /-->
<!-- wp:separator {"className":"rule"} -->
<hr class="wp-block-separator has-alpha-channel-opacity rule"/>
<!-- /wp:separator -->
<!-- wp:group {"className":"stack-sm"} -->
<div class="wp-block-group stack-sm"><!-- wp:heading {"className":"h3"} -->
<h2 class="wp-block-heading h3">What happens on the call</h2>
<!-- /wp:heading -->
<!-- wp:list {"className":"fit fit--yes fit--stack"} -->
<ul class="wp-block-list fit fit--yes fit--stack"><!-- wp:list-item -->
<li>We talk through your business, customers and current marketing</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>I share first observations on your website and search visibility (I’ll look before we meet)</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>We decide together whether a growth audit makes sense</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"testimonial testimonial--sm"} -->
<div class="wp-block-group testimonial testimonial--sm"><!-- wp:quote -->
<blockquote class="wp-block-quote "><!-- wp:paragraph -->
<p><span class="tbd">[One short client testimonial]</span></p>
<!-- /wp:paragraph --></blockquote>
<!-- /wp:quote -->
<!-- wp:paragraph {"className":"testimonial__by"} -->
<p class="testimonial__by"><span class="tbd">[Name, Company]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></aside>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
