<?php
/**
 * Title: Page: Thank You
 * Slug: hpv/page-strategy-call-thank-you
 * Categories: hpv-pages
 * Description: Thanks for booking a strategy call.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner","anchor":"hero"} -->
<section class="wp-block-group hero hero--inner" id="hero"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"hero__text col-8"} -->
<div class="wp-block-group hero__text col-8"><!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Booked</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display">Thank you. <span class="scribble">Talk soon</span>.</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">A confirmation email is on its way. Before we meet, I’ll look at your website and your search visibility, so we can spend the 30 minutes on what matters.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"body"} -->
<p class="body">If something changes, just reply to the confirmation email. I personally reply to every message within one business hour.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top"} -->
<section class="wp-block-group section section--flush-top"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label">While you wait</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Worth a look before the call</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"insights"} -->
<div class="wp-block-group insights"><!-- wp:group {"tagName":"article","className":"insight-card"} -->
<article class="wp-block-group insight-card"><!-- wp:paragraph {"className":"insight-card__topic"} -->
<p class="insight-card__topic">Case study</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"insight-card__title"} -->
<h3 class="wp-block-heading insight-card__title"><a href="<?php echo esc_url( home_url( '/case-studies/imperial-kitchens/' ) ); ?>">A Fort Myers remodeler’s website, rebuilt to sell</a></h3>
<!-- /wp:heading --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"insight-card"} -->
<article class="wp-block-group insight-card"><!-- wp:paragraph {"className":"insight-card__topic"} -->
<p class="insight-card__topic">Websites</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"insight-card__title"} -->
<h3 class="wp-block-heading insight-card__title"><a href="<?php echo esc_url( home_url( '/insights/website-traffic-no-calls/' ) ); ?>">Why your website gets traffic but no calls</a></h3>
<!-- /wp:heading --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"insight-card"} -->
<article class="wp-block-group insight-card"><!-- wp:paragraph {"className":"insight-card__topic"} -->
<p class="insight-card__topic">About</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"insight-card__title"} -->
<h3 class="wp-block-heading insight-card__title"><a href="<?php echo esc_url( home_url( '/about/' ) ); ?>">Who you’ll be talking to</a></h3>
<!-- /wp:heading --></article>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
