<?php
/**
 * Title: Page: Website Design & Development
 * Slug: hpv/page-service-website
 * Categories: hpv-pages
 * Description: Strategic website design and development for Florida service businesses. Fast, search-ready WordPress sites built to turn visits into calls.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner","anchor":"hero"} -->
<section class="wp-block-group hero hero--inner" id="hero"><!-- wp:group {"className":"wrap grid hero__grid"} -->
<div class="wp-block-group wrap grid hero__grid"><!-- wp:group {"className":"hero__text col-8"} -->
<div class="wp-block-group hero__text col-8"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Website Design & Development · Fort Myers & Naples</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display">Not a website. A <span class="scribble">digital sales system</span>.</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Strategic website design and development for Southwest Florida businesses — built around how your customers decide, and measured by the calls and requests it creates.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a> <a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">See website case studies <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"problem"} -->
<section class="wp-block-group section section--flush-top" id="problem"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:heading {"className":"h2 col-7"} -->
<h2 class="wp-block-heading h2 col-7">Most business websites are brochures. Yours should sell.</h2>
<!-- /wp:heading -->
<!-- wp:group {"className":"col-5 body"} -->
<div class="wp-block-group col-5 body"><!-- wp:paragraph -->
<p>A good-looking website isn’t the goal. The goal is a website that makes the right people pick up the phone. That means clear positioning above the fold, proof in the right places, pages built for how people search, and a path to contact that works on a phone in a parking lot.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"recent"} -->
<section class="wp-block-group section section--flush-top" id="recent"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label">Recent websites</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Recent websites by HelloProVision</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"work"} -->
<div class="wp-block-group work"><!-- wp:group {"tagName":"article","className":"work-item"} -->
<article class="wp-block-group work-item"><!-- wp:hpv/project {"name":"Factory FM","src":"projects/factory-fm-1","ratio":"land","tone":3} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name">Factory FM</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item"} -->
<article class="wp-block-group work-item"><!-- wp:hpv/project {"name":"Raven Protect","src":"projects/raven-protect-1","ratio":"land","tone":4} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name">Raven Protect</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item"} -->
<article class="wp-block-group work-item"><!-- wp:hpv/project {"name":"Kaeri","src":"projects/kaeri-1","ratio":"land","tone":1} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name">Kaeri</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"includes"} -->
<section class="wp-block-group section bg-paper" id="includes"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">01</span> What’s included</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">What a digital sales system includes</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"features features--3"} -->
<div class="wp-block-group features features--3"><!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">01</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Research before design</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Competitor review, customer search behavior and the questions buyers ask before they call.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">02</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Positioning and conversion copy</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Messaging that answers “why you” in seconds, with proof placed where doubts appear.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">03</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Premium, custom design</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>A design that matches the quality of your work — not a recycled template.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">04</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Fast, search-ready development</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>WordPress built for speed, Core Web Vitals and SEO from day one, with no fragile page builder.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">05</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Lead capture and tracking</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Forms, click-to-call, booking and analytics, so you know exactly which pages and searches bring customers.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">06</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Easy to manage</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>You can update text, projects and photos yourself, without calling a developer.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"project"} -->
<section class="wp-block-group section" id="project"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">02</span> Timeline</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">How the project runs</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Typically 6–10 weeks from kickoff to launch, followed by 30 days of tuning.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"timeline"} -->
<div class="wp-block-group timeline"><!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"timeline__when"} -->
<p class="timeline__when">Week 1</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Discovery</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Goals, offer, customers and competitors.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"timeline__when"} -->
<p class="timeline__when">Week 2</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Strategy and sitemap</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Pages, keywords and conversion paths.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"timeline__when"} -->
<p class="timeline__when">Weeks 3–5</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Copy and design</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Messaging and visual design, reviewed together.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"timeline__when"} -->
<p class="timeline__when">Weeks 5–7</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Build</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Development, content and tracking.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"timeline__when"} -->
<p class="timeline__when">Week 8+</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Launch and improve</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Quality checks, launch, then 30 days of tuning.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-accent","anchor":"for-whom"} -->
<section class="wp-block-group section bg-accent" id="for-whom"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-6 stack-lg"} -->
<div class="wp-block-group col-6 stack-lg"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">03</span> Who it’s for</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Built for Florida service businesses</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"body"} -->
<p class="body">Contractors, remodelers, home services, hospitality and local professional firms — businesses where one new client is worth thousands.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"case-card col-5 start-8"} -->
<article class="wp-block-group case-card col-5 start-8"><!-- wp:hpv/project {"name":"Imperial Kitchens","src":"projects/imperial-kitchens-1","ratio":"land","tone":2} /-->
<!-- wp:paragraph {"className":"case-card__meta"} -->
<p class="case-card__meta"><span class="tbd">[Imperial Kitchens]</span> · Fort Myers</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"case-card__title"} -->
<h3 class="wp-block-heading case-card__title">A remodeler’s website rebuilt around how homeowners choose</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/imperial-kitchens/' ) ); ?>">Read the case study <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></article>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"faq"} -->
<section class="wp-block-group section" id="faq"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-4 stack"} -->
<div class="wp-block-group col-4 stack"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Website design FAQ</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"small"} -->
<p class="small">More reading: <a class="link" href="<?php echo esc_url( home_url( '/insights/website-traffic-no-calls/' ) ); ?>">why a website gets traffic but no calls</a>.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-8 faq"} -->
<div class="wp-block-group col-8 faq"><!-- wp:details -->
<details class="wp-block-details"><summary>How long does a website take?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Typically 6–10 weeks, depending on pages and content readiness.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Do you use templates?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">No. Every site is designed for your business, on a fast, clean WordPress foundation.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Will I be able to edit it?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Yes. You’ll edit pages and projects in the standard WordPress editor.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Do you write the copy?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Yes — copy is part of the strategy, not an add-on.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>What about SEO?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Every build includes technical SEO and on-page structure. Ongoing growth is covered by <a class="link" href="<?php echo esc_url( home_url( '/services/local-seo/' ) ); ?>">Local SEO</a>.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-ink on-dark","anchor":"final-cta"} -->
<section class="wp-block-group section bg-ink on-dark" id="final-cta"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"final-cta"} -->
<div class="wp-block-group final-cta"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Let’s build a website that earns its keep.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn btn--on-dark" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
