<?php
/**
 * Title: Page: About
 * Slug: hpv/page-about
 * Categories: hpv-pages
 * Description: Entrepreneur, founder of HelloProVision and digital growth strategist. The story, principles and proof behind the work with Florida businesses.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner","anchor":"hero"} -->
<section class="wp-block-group hero hero--inner" id="hero"><!-- wp:group {"className":"wrap grid hero__grid"} -->
<div class="wp-block-group wrap grid hero__grid"><!-- wp:group {"className":"hero__text col-7"} -->
<div class="wp-block-group hero__text col-7"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">About Áron Ritók-Filip</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display">I don’t just advise businesses. I <span class="scribble">build and grow them</span> myself.</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">I’m Áron Ritók-Filip — founder of HelloProVision and a digital growth strategist working with Florida businesses. I help owners turn their online presence into a system that brings in qualified opportunities, predictably.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-5 hero__media"} -->
<div class="wp-block-group col-5 hero__media"><!-- wp:hpv/photo {"src":"people/aron-environmental","ratio":"portrait","alt":"Áron Ritók-Filip in Southwest Florida","note":"Environmental portrait|Shoot pending","eager":true} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"story"} -->
<section class="wp-block-group section section--flush-top" id="story"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-4"} -->
<div class="wp-block-group col-4"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">01</span> Story</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-7 start-6 stack-lg"} -->
<div class="wp-block-group col-7 start-6 stack-lg"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">An entrepreneur first</h2>
<!-- /wp:heading -->
<!-- wp:group {"className":"body stack-sm"} -->
<div class="wp-block-group body stack-sm"><!-- wp:paragraph -->
<p>I didn’t learn growth from a textbook or inside an agency. I learned it by building businesses — making payroll, choosing where to spend the next dollar, and living with the result.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tbd"} -->
<p class="tbd">[Verified story, 2–3 short paragraphs. Suggested beats: where you started in Europe; the first business or project you built and what it taught you; founding HelloProVision and the kind of companies you grew — e.g. Tank Empire Budapest, Factory FM, Raven Protect — with one concrete, verifiable result.]</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>That experience shapes how I work today. When I look at a client’s website or marketing, I see it the way an owner does: as an investment that has to pay back.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"florida"} -->
<section class="wp-block-group section bg-paper" id="florida"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-4"} -->
<div class="wp-block-group col-4"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">02</span> Florida</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-7 start-6 stack-lg"} -->
<div class="wp-block-group col-7 start-6 stack-lg"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">A European perspective, built for Florida</h2>
<!-- /wp:heading -->
<!-- wp:group {"className":"body stack-sm"} -->
<div class="wp-block-group body stack-sm"><!-- wp:paragraph {"className":"tbd"} -->
<p class="tbd">[Verified: when and why you moved to Florida, and what you’ve built here since.]</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Working across markets taught me something useful: the fundamentals of growth travel well, but the details never do. How a homeowner in Naples chooses a contractor is different from how a business buyer in Budapest chooses a partner. Good strategy starts with that local reality — who your customers are, how they search, and what makes them trust someone.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Southwest Florida is a remarkable place to build a business: fast population growth, seasonal rhythms, a premium market and fierce local competition. It rewards businesses that are easy to find, easy to trust and easy to contact. That’s exactly what I help build.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"principles"} -->
<section class="wp-block-group section" id="principles"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">03</span> Principles</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">How I think about growth</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"principles"} -->
<div class="wp-block-group principles"><!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Strategy means choosing.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>If everything is a priority, nothing is. Good strategy says what to do first — and what not to do yet.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Numbers need context.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>I start from data, but a metric rarely explains itself. I connect the numbers to your customers, your team and your decisions.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">A plan you can execute beats a perfect plan.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Recommendations have to fit your budget, your people and your pace.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">Technology is a tool, not a strategy.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Websites, SEO, ads and AI matter only when they solve a clear business problem.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"focus"} -->
<section class="wp-block-group section section--flush-top" id="focus"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-4"} -->
<div class="wp-block-group col-4"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">04</span> Focus</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-7 start-6 stack-lg"} -->
<div class="wp-block-group col-7 start-6 stack-lg"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">What I focus on</h2>
<!-- /wp:heading -->
<!-- wp:group {"className":"body stack-sm"} -->
<div class="wp-block-group body stack-sm"><!-- wp:paragraph -->
<p>My core work is <a class="link" href="<?php echo esc_url( home_url( '/services/digital-growth-strategy/' ) ); ?>">digital growth strategy for established Florida businesses</a>, supported by three disciplines: <a class="link" href="<?php echo esc_url( home_url( '/services/website-design-development/' ) ); ?>">strategic website design and development</a>, <a class="link" href="<?php echo esc_url( home_url( '/services/local-seo/' ) ); ?>">local SEO and search growth</a>, and conversion-focused digital marketing. When something falls outside what I do best, I’ll tell you — and point you to someone who does it better.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"built"} -->
<section class="wp-block-group section" id="built"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">05</span> Built and grown</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Businesses I’ve built and grown with HelloProVision</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"work"} -->
<div class="wp-block-group work"><!-- wp:group {"tagName":"article","className":"work-item work-item--lg"} -->
<article class="wp-block-group work-item work-item--lg"><!-- wp:hpv/project {"name":"Tank Empire Budapest","src":"projects/tank-empire-budapest-1","ratio":"wide","tone":5} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name">Tank Empire Budapest</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat">Budapest, Hungary</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item work-item--md"} -->
<article class="wp-block-group work-item work-item--md"><!-- wp:hpv/project {"name":"Factory FM","src":"projects/factory-fm-1","ratio":"square","tone":3} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name">Factory FM</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[market]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item work-item--md"} -->
<article class="wp-block-group work-item work-item--md"><!-- wp:hpv/project {"name":"Raven Protect","src":"projects/raven-protect-1","ratio":"square","tone":4} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name">Raven Protect</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[market]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item work-item--lg"} -->
<article class="wp-block-group work-item work-item--lg"><!-- wp:hpv/project {"name":"Imperial Kitchens","src":"projects/imperial-kitchens-1","ratio":"wide","tone":2} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name">Imperial Kitchens</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat">Fort Myers, Florida</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group --></div>
<!-- /wp:group -->
<!-- wp:paragraph {"className":"mt-6"} -->
<p class="mt-6"><a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">See the case studies <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-accent","anchor":"proof"} -->
<section class="wp-block-group section bg-accent" id="proof"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">06</span> Proof</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Experience and proof</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"stats"} -->
<div class="wp-block-group stats"><!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[N]</span></span><span class="stat__ctx">businesses built or co-founded</span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[N]</span></span><span class="stat__ctx">projects delivered with HelloProVision</span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[N]</span></span><span class="stat__ctx">markets worked in — <span class="tbd">[Hungary, US, …]</span></span></p>
<!-- /wp:paragraph -->
<!-- wp:hpv/case-result /--></div>
<!-- /wp:group -->
<!-- wp:paragraph {"className":"small mt-6"} -->
<p class="small mt-6"><span class="tbd">[Optional: certifications, speaking, publications — only real ones.]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"beyond"} -->
<section class="wp-block-group section" id="beyond"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-5"} -->
<div class="wp-block-group col-5"><!-- wp:hpv/photo {"src":"people/aron-florida","ratio":"land","alt":"Morning in Southwest Florida","note":"Florida lifestyle · 3:2|Shoot pending"} /--></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-6 start-7 stack-lg"} -->
<div class="wp-block-group col-6 start-7 stack-lg"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">07</span> Beyond work</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Beyond work</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"body tbd"} -->
<p class="body tbd">[2–4 specific, memorable personal details — e.g. what you’re building next, a Florida ritual, what you’re reading or learning. Avoid “I love travel and growth.”]</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-ink on-dark","anchor":"final-cta"} -->
<section class="wp-block-group section bg-ink on-dark" id="final-cta"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"final-cta"} -->
<div class="wp-block-group final-cta"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Let’s talk about your next stage of growth</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">If you’re an owner looking for a strategic partner who builds, not just advises, start with a 30-minute call. We’ll look at where you are and decide honestly whether working together makes sense.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn btn--on-dark" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a> <a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Or see the case studies <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
