<?php
/**
 * Title: Page: Privacy Policy
 * Slug: hpv/page-privacy-policy
 * Categories: hpv-pages
 * Description: What personal information this website collects, why, and the choices you have.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner"} -->
<section class="wp-block-group hero hero--inner"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:group {"className":"legal mt-4"} -->
<div class="wp-block-group legal mt-4"><!-- wp:heading {"level":1,"className":"h1"} -->
<h1 class="wp-block-heading h1">Privacy policy</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"caption"} -->
<p class="caption">Last updated: <span class="tbd">[launch date]</span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"draft-note"} -->
<p class="draft-note">Draft for review by a Florida-licensed attorney before launch. Replace every marked item with the final business details.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>This website is operated by <span class="tbd">[HelloProVision LLC]</span> (“we”, “us”), the studio founded by Áron Ritók-Filip. This policy explains what information we collect when you use this site, how we use it and the choices you have.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Information you give us</h2>
<!-- /wp:heading -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li><strong>Strategy call requests:</strong> name, email, phone, company website, industry, city, main challenge, marketing budget range and timing.</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li><strong>Growth Scorecard:</strong> name, email, company website and your answers to the scorecard questions.</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li><strong>Email and phone:</strong> anything you choose to send us directly.</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Information collected automatically</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>If you accept analytics cookies, we use Google Analytics 4 to understand which pages are visited and which lead to inquiries. It collects information such as pages viewed, approximate location, device and browser type. We don’t use it to identify you personally. <span class="tbd">[Confirm tools in use: GA4, call tracking, booking tool.]</span></p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">How we use your information</h2>
<!-- /wp:heading -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>To reply to your request and schedule a call</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>To send your scorecard results and up to three follow-up emails related to them</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>To prepare for our conversation, for example by reviewing your website</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>To improve this website</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
<!-- wp:paragraph -->
<p>We don’t sell your personal information, and we don’t share it except with service providers who help us run this site (hosting, email, booking and analytics), under obligations to protect it.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Your choices</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>You can unsubscribe from any email with one click, decline analytics cookies, and ask us to access, correct or delete the information we hold about you by contacting us below.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">How long we keep it</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>We keep inquiry information for as long as needed to respond and for our business records, then delete it. <span class="tbd">[Set a retention period, e.g. 24 months.]</span></p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Children</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>This site is intended for business owners and is not directed at children under 13.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Contact</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><span class="tbd">[HelloProVision LLC, mailing address]</span> · <span class="tbd">[hello@domain]</span> · <span class="tbd">[+1 (239) 000-0000]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
