<?php
/**
 * Title: Page: Terms of Use
 * Slug: hpv/page-terms
 * Categories: hpv-pages
 * Description: The terms that apply when you use this website.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner"} -->
<section class="wp-block-group hero hero--inner"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:group {"className":"legal mt-4"} -->
<div class="wp-block-group legal mt-4"><!-- wp:heading {"level":1,"className":"h1"} -->
<h1 class="wp-block-heading h1">Terms of use</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"caption"} -->
<p class="caption">Last updated: <span class="tbd">[launch date]</span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"draft-note"} -->
<p class="draft-note">Draft for review by a Florida-licensed attorney before launch.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>By using this website you agree to these terms. The site is operated by <span class="tbd">[HelloProVision LLC]</span>.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Information on this site</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Articles, the Growth Scorecard and other content are general information, not professional advice for your specific situation. Results described in case studies are specific to those clients and are not a promise of future results. No one can guarantee search rankings, and we don’t.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Services</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Any work we do together is governed by a separate written proposal or agreement, which takes precedence over these terms.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Intellectual property</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>The text, design, images and code on this site belong to us or are used with permission. Client names and logos belong to their owners and appear with their permission.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Links</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>We link to other websites for convenience. We aren’t responsible for their content or privacy practices.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Limitation of liability</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>This site is provided “as is”. To the extent permitted by law, we aren’t liable for damages arising from its use.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Governing law</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>These terms are governed by the laws of the State of Florida. <span class="tbd">[Confirm venue, e.g. Lee County, Florida.]</span></p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Contact</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><span class="tbd">[hello@domain]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
