<?php
/**
 * Title: Page: Case Studies
 * Slug: hpv/page-case-studies
 * Categories: hpv-pages
 * Description: Real projects, real numbers: websites, local SEO and growth strategy for service and hospitality businesses.
 * Post Types: page
 * Inserter: no
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner","anchor":"hero"} -->
<section class="wp-block-group hero hero--inner" id="hero"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:paragraph {"className":"sticker"} -->
<p class="sticker">Real work. Real numbers.</p>
<!-- /wp:paragraph -->
<!-- wp:group {"className":"hero__text col-8"} -->
<div class="wp-block-group hero__text col-8"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Case Studies</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display">Proof, <span class="scribble">not promises</span>.</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Short business stories: what wasn’t working, what we decided, what we built and what changed — with every number tied to a timeframe and a source.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"cases"} -->
<section class="wp-block-group section section--flush-top" id="cases"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:hpv/case-grid {"layout":"hub","count":12,"filter":true,"upcoming":"Factory FM, Raven Protect, Tank Empire Budapest, Mandala, Kaeri"} /--></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-ink on-dark","anchor":"final-cta"} -->
<section class="wp-block-group section bg-ink on-dark" id="final-cta"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"final-cta"} -->
<div class="wp-block-group final-cta"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Facing a similar challenge?</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Tell me where growth is stuck. In 30 minutes we’ll know whether a growth audit makes sense.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn btn--on-dark" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
