<?php
/**
 * Title: Page: Insights
 * Slug: hpv/page-insights
 * Categories: hpv-pages
 * Description: Practical thinking on websites, local search and growth for Southwest Florida service businesses — written for owners, not marketers.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner","anchor":"hero"} -->
<section class="wp-block-group hero hero--inner" id="hero"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"hero__text col-8"} -->
<div class="wp-block-group hero__text col-8"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Insights</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display">Insights for Florida <span class="scribble">business owners</span></h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Practical thinking on websites, local search and growth — written for owners, not marketers.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"websites"} -->
<section class="wp-block-group section section--flush-top" id="websites"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label">Websites</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Websites that sell</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"small"} -->
<p class="small">Related service: <a class="link" href="<?php echo esc_url( home_url( '/services/website-design-development/' ) ); ?>">Website Design &amp; Development</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:hpv/insights {"topic":"websites","count":3,"fill":true} /--></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"local-seo"} -->
<section class="wp-block-group section bg-paper" id="local-seo"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label">Local SEO</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Getting found locally</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"small"} -->
<p class="small">Related service: <a class="link" href="<?php echo esc_url( home_url( '/services/local-seo/' ) ); ?>">Local SEO</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:hpv/insights {"topic":"local-seo","count":3,"fill":true} /--></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"growth"} -->
<section class="wp-block-group section" id="growth"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label">Growth</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Growth and conversion</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"small"} -->
<p class="small">Related service: <a class="link" href="<?php echo esc_url( home_url( '/services/digital-growth-strategy/' ) ); ?>">Digital Growth Strategy</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:hpv/insights {"topic":"growth","count":3,"fill":true} /--></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section--tight bg-mark","anchor":"scorecard"} -->
<section class="wp-block-group section--tight bg-mark" id="scorecard"><!-- wp:group {"className":"wrap cta-band"} -->
<div class="wp-block-group wrap cta-band"><!-- wp:group {"className":"stack"} -->
<div class="wp-block-group stack"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Find your bottleneck in 5 minutes.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>The Digital Growth Scorecard scores positioning, website, search visibility, conversion and follow-up — and tells you which to fix first.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph {"className":"cta-band__action"} -->
<p class="cta-band__action"><a class="btn" href="<?php echo esc_url( home_url( '/growth-scorecard/' ) ); ?>">Take the scorecard <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
