<?php
/**
 * Title: Page: Digital Growth Strategy
 * Slug: hpv/page-service-strategy
 * Categories: hpv-pages
 * Description: Find the growth hiding across your website, marketing and customer journey. A research-based roadmap for established Florida businesses.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner","anchor":"hero"} -->
<section class="wp-block-group hero hero--inner" id="hero"><!-- wp:group {"className":"wrap grid hero__grid"} -->
<div class="wp-block-group wrap grid hero__grid"><!-- wp:group {"className":"hero__text col-7"} -->
<div class="wp-block-group hero__text col-7"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Digital Growth Strategy · Florida</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display">Find the <span class="scribble">growth</span> hiding in your business.</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Digital growth strategy for Florida business owners — uncovering opportunities across your website, marketing and customer journey, then turning them into a clear plan.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-5 hero__media"} -->
<div class="wp-block-group col-5 hero__media"><!-- wp:hpv/photo {"src":"people/aron-strategy","ratio":"land","alt":"Áron Ritók-Filip mapping a growth strategy with printed sitemaps and wireframes","note":"Strategy moment · 3:2|Shoot pending","eager":true} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"problem"} -->
<section class="wp-block-group section section--flush-top" id="problem"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:heading {"className":"h2 col-6"} -->
<h2 class="wp-block-heading h2 col-6">When more marketing isn’t the answer</h2>
<!-- /wp:heading -->
<!-- wp:group {"className":"col-5 start-8 body stack-sm"} -->
<div class="wp-block-group col-5 start-8 body stack-sm"><!-- wp:paragraph -->
<p>Many owners respond to slow growth by spending more on ads or hiring another agency. Often the real bottleneck sits somewhere else: an unclear offer, a website that doesn’t convert, leads that go unanswered for hours, or no data on what actually works.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"text-ink"} -->
<p class="text-ink">Strategy finds that bottleneck first — so every dollar after it works harder.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"look"} -->
<section class="wp-block-group section bg-paper" id="look"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">01</span> Scope</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">What we look at</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"features features--3"} -->
<div class="wp-block-group features features--3"><!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Market and competitors</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Where the demand is and who’s capturing it.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Positioning and offer</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Why customers should choose you, in their words.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Website and conversion</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Where visitors drop off and why.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Search and paid acquisition</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Which channels bring profitable customers.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Customer journey and follow-up</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>What happens after someone reaches out.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Measurement</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>The few numbers that show whether growth is working.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"get"} -->
<section class="wp-block-group section" id="get"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">02</span> Deliverables</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">What you get</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process process--3"} -->
<div class="wp-block-group process process--3"><!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">01</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Growth audit</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>A clear picture of where you are today, with evidence.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">02</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">90-day growth roadmap</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Prioritized actions, owners, budgets and targets.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">03</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Ongoing strategic partnership <span class="muted">(optional)</span></h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Monthly strategy sessions, performance reviews and a partner for the decisions in between.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-accent","anchor":"for-whom"} -->
<section class="wp-block-group section bg-accent" id="for-whom"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-6 stack-lg"} -->
<div class="wp-block-group col-6 stack-lg"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">03</span> Who it’s for</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Who this is for</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-5 start-8 body stack-sm"} -->
<div class="wp-block-group col-5 start-8 body stack-sm"><!-- wp:paragraph -->
<p>Established businesses with a working model and an owner ready to invest in structured growth — especially home services, contractors, hospitality and local professional firms.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">See client results <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"faq"} -->
<section class="wp-block-group section" id="faq"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-4"} -->
<div class="wp-block-group col-4"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Digital growth strategy FAQ</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-8 faq"} -->
<div class="wp-block-group col-8 faq"><!-- wp:details -->
<details class="wp-block-details"><summary>Is this just consulting?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">It’s strategy connected to execution. If you want us to build it, HelloProVision can — see <a class="link" href="<?php echo esc_url( home_url( '/services/website-design-development/' ) ); ?>">website design</a> and <a class="link" href="<?php echo esc_url( home_url( '/services/local-seo/' ) ); ?>">local SEO</a>.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>How is this different from an agency?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">You work directly with me, and we measure qualified opportunities, not activity.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>What does it cost?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a"><span class="tbd">[Audit fixed fee; retainer range — confirm.]</span></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-ink on-dark","anchor":"final-cta"} -->
<section class="wp-block-group section bg-ink on-dark" id="final-cta"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"final-cta"} -->
<div class="wp-block-group final-cta"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Let’s find your biggest growth opportunity.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn btn--on-dark" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
