<?php
/**
 * Title: Page: Local SEO
 * Slug: hpv/page-service-local-seo
 * Categories: hpv-pages
 * Description: Get found in Google Maps and search across Fort Myers, Naples and Cape Coral. Local SEO with honest reporting on calls and leads.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner","anchor":"hero"} -->
<section class="wp-block-group hero hero--inner" id="hero"><!-- wp:group {"className":"wrap grid hero__grid"} -->
<div class="wp-block-group wrap grid hero__grid"><!-- wp:group {"className":"hero__text col-8"} -->
<div class="wp-block-group hero__text col-8"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Local SEO · Southwest Florida</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display">Be the business Florida customers <span class="scribble">find first</span>.</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Local SEO for Fort Myers, Naples and Cape Coral businesses that want to show up in Google Maps and search results when customers are ready to buy.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a> <a class="arrow-link" href="<?php echo esc_url( home_url( '/growth-scorecard/' ) ); ?>">Take the Growth Scorecard <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"problem"} -->
<section class="wp-block-group section section--flush-top" id="problem"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:heading {"className":"h2 col-7"} -->
<h2 class="wp-block-heading h2 col-7">Your customers are searching. Are they finding you?</h2>
<!-- /wp:heading -->
<!-- wp:group {"className":"col-5 body"} -->
<div class="wp-block-group col-5 body"><!-- wp:paragraph -->
<p>When someone in Cape Coral searches “kitchen remodeler near me” or “pool builder Naples,” they call one of the first three businesses they see. Local SEO is how you become one of them — and stay there.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"includes"} -->
<section class="wp-block-group section bg-paper" id="includes"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">01</span> What’s included</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">What Local SEO growth includes</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"features features--3"} -->
<div class="wp-block-group features features--3"><!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">01</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Google Business Profile optimization</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Categories, services, photos, posts and Q&A — the profile that powers map results.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">02</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Service and location pages</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Pages built for real searches in the areas you serve, with local proof on every page.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">03</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Reviews and reputation</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>A simple system to ask happy customers for reviews and respond professionally.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">04</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Technical SEO</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Speed, indexing, structured data and site health, so Google understands every page.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">05</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Local authority</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Consistent listings, local partnerships and mentions that build trust with Google and customers.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">06</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Reporting that matters</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Monthly reporting on calls, form requests and direction requests — not just rankings.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"honest"} -->
<section class="wp-block-group section" id="honest"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-8 start-3 honest"} -->
<div class="wp-block-group col-8 start-3 honest"><!-- wp:paragraph {"className":"label label--plain"} -->
<p class="label label--plain"><span class="label__num">02</span> Expectations</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">An honest word on SEO</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"body"} -->
<p class="body">No one can guarantee rankings, and anyone who does is guessing. What I promise is a clear plan, consistent execution and transparent reporting. Most local businesses see meaningful movement within 3–6 months, depending on competition.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"reading"} -->
<section class="wp-block-group section section--flush-top" id="reading"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">03</span> Reading</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">From the Local SEO notebook</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:hpv/insights {"topic":"local-seo","count":3,"fill":true} /--></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"local-work"} -->
<section class="wp-block-group section section--flush-top" id="local-work"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-5 stack-lg"} -->
<div class="wp-block-group col-5 stack-lg"><!-- wp:paragraph {"className":"label"} -->
<p class="label">Local proof</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Local search, built into every site we launch</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"body"} -->
<p class="body">Service pages, map-ready business details and review requests are part of the build — like the Fort Myers remodeling site below.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/imperial-kitchens/' ) ); ?>">Read the Imperial Kitchens case study <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-6 start-7"} -->
<div class="wp-block-group col-6 start-7"><!-- wp:hpv/project {"name":"Imperial Kitchens","src":"projects/imperial-kitchens-4","ratio":"land","tone":5,"alt":"Imperial Kitchens service page built for local search"} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"faq"} -->
<section class="wp-block-group section bg-paper" id="faq"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-4"} -->
<div class="wp-block-group col-4"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Local SEO FAQ</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-8 faq"} -->
<div class="wp-block-group col-8 faq"><!-- wp:details -->
<details class="wp-block-details"><summary>Do you work outside Fort Myers?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Yes — across Southwest Florida and statewide for the right fit.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Do I need a new website for SEO?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Not always. We start with an audit.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Is there a long contract?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a"><span class="tbd">[Confirm terms, e.g. 6-month minimum, then month-to-month.]</span></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>What does a typical month include?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a"><span class="tbd">[Confirm scope.]</span></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-ink on-dark","anchor":"final-cta"} -->
<section class="wp-block-group section bg-ink on-dark" id="final-cta"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"final-cta"} -->
<div class="wp-block-group final-cta"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Find out where you stand in local search.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn btn--on-dark" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
