<?php
/**
 * Title: Page: Accessibility Statement
 * Slug: hpv/page-accessibility
 * Categories: hpv-pages
 * Description: Our commitment to an accessible website, the standard we follow and how to report a problem.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner"} -->
<section class="wp-block-group hero hero--inner"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:group {"className":"legal mt-4"} -->
<div class="wp-block-group legal mt-4"><!-- wp:heading {"level":1,"className":"h1"} -->
<h1 class="wp-block-heading h1">Accessibility statement</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"caption"} -->
<p class="caption">Last updated: <span class="tbd">[launch date]</span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>I want every business owner to be able to use this website, including people who use screen readers, keyboard navigation, magnification or other assistive technology.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">The standard we follow</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>This site is designed and tested to meet the Web Content Accessibility Guidelines (WCAG) 2.2, level AA. In practice that means:</p>
<!-- /wp:paragraph -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Text contrast of at least 4.5:1 against its background</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Visible focus states and full keyboard access for menus, forms and accordions</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Tap targets of at least 44 × 44 pixels</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Headings in a logical order and descriptive link text</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Alternative text for meaningful images</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Form fields with visible labels and clear error messages</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Animation turned off when your device asks for reduced motion</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Known limitations</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Third-party tools, such as the booking calendar, are provided by other companies. We choose tools with good accessibility, but can’t fully control them. If one gets in your way, contact me and I’ll book the call for you directly.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Report a problem</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>If something on this site is hard to use, please tell me. I aim to reply within two business days.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Email: <span class="tbd">[hello@domain]</span> · Phone: <span class="tbd">[+1 (239) 000-0000]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
