<?php
/**
 * Title: Page: Services
 * Slug: hpv/page-services
 * Categories: hpv-pages
 * Description: Strategy, website design and local SEO, connected into one growth system for Southwest Florida service businesses.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner","anchor":"hero"} -->
<section class="wp-block-group hero hero--inner" id="hero"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:paragraph {"className":"sticker sticker--pink"} -->
<p class="sticker sticker--pink">One system. Three ways.</p>
<!-- /wp:paragraph -->
<!-- wp:group {"className":"hero__text col-9"} -->
<div class="wp-block-group hero__text col-9"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Services · Southwest Florida</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"h1"} -->
<h1 class="wp-block-heading h1">One growth system. <span class="scribble">Three ways</span> to build it.</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Strategy, website design and local SEO for established Florida service businesses — planned together, built together and measured by the qualified opportunities they create.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"services"} -->
<section class="wp-block-group section section--flush-top" id="services"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"services"} -->
<div class="wp-block-group services"><!-- wp:group {"tagName":"article","className":"service-card service-card--wide"} -->
<article class="wp-block-group service-card service-card--wide"><!-- wp:group {"className":"service-card__head"} -->
<div class="wp-block-group service-card__head"><!-- wp:paragraph {"className":"service-card__num"} -->
<p class="service-card__num">01 · Where most engagements start</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"service-card__title"} -->
<h2 class="wp-block-heading service-card__title">Digital Growth Strategy</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"stack"} -->
<div class="wp-block-group stack"><!-- wp:paragraph {"className":"service-card__pos"} -->
<p class="service-card__pos">Find the opportunities hiding between your website, your marketing and your customer journey.</p>
<!-- /wp:paragraph -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Growth audit with evidence, not opinions</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>90-day roadmap ranked by business impact</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Optional monthly strategic partnership</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/services/digital-growth-strategy/' ) ); ?>">Explore Digital Growth Strategy <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"service-card"} -->
<article class="wp-block-group service-card"><!-- wp:paragraph {"className":"service-card__num"} -->
<p class="service-card__num">02</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"service-card__title"} -->
<h2 class="wp-block-heading service-card__title">Website Design & Development</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"service-card__pos"} -->
<p class="service-card__pos">Not a website. A digital sales system — built around how your buyers decide.</p>
<!-- /wp:paragraph -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Research, positioning and conversion copy</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Custom design on a fast WordPress build</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Lead capture, click-to-call and tracking</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/services/website-design-development/' ) ); ?>">Explore Website Design &amp; Development <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"service-card"} -->
<article class="wp-block-group service-card"><!-- wp:paragraph {"className":"service-card__num"} -->
<p class="service-card__num">03</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"service-card__title"} -->
<h2 class="wp-block-heading service-card__title">Local SEO</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"service-card__pos"} -->
<p class="service-card__pos">Be the business Fort Myers, Naples and Cape Coral customers find first.</p>
<!-- /wp:paragraph -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Google Business Profile and map pack</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Service and location pages with local proof</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Reviews, reputation and honest reporting</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/services/local-seo/' ) ); ?>">Explore Local SEO <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></article>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"projects"} -->
<section class="wp-block-group section section--flush-top" id="projects"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"strip"} -->
<div class="wp-block-group strip"><!-- wp:hpv/project {"name":"Imperial Kitchens","src":"projects/imperial-kitchens-1","ratio":"land","tone":2} /-->
<!-- wp:hpv/project {"name":"Factory FM","src":"projects/factory-fm-1","ratio":"land","tone":3} /-->
<!-- wp:hpv/project {"name":"Tank Empire Budapest","src":"projects/tank-empire-budapest-1","ratio":"land","tone":5} /-->
<!-- wp:hpv/project {"name":"Mandala","src":"projects/mandala-1","ratio":"land","tone":6} /-->
<!-- wp:hpv/project {"name":"Kaeri","src":"projects/kaeri-1","ratio":"land","tone":1} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"connected"} -->
<section class="wp-block-group section bg-paper" id="connected"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-5"} -->
<div class="wp-block-group col-5"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">01</span> Why connected</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2 mt-4"} -->
<h2 class="wp-block-heading h2 mt-4">Separate vendors optimize separate numbers.</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-6 start-7 body stack-sm"} -->
<div class="wp-block-group col-6 start-7 body stack-sm"><!-- wp:paragraph -->
<p>A web designer is measured on launch day. An SEO provider reports rankings. An ad agency reports clicks. None of those is the number an owner cares about: how many qualified customers reached out this month, and how many became jobs.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Working as one system means one plan, one set of tracking and one person accountable for the result. You work with me directly; my team at HelloProVision handles the build.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"mt-4"} -->
<p class="mt-4"><a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">See how it played out for clients <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"compare"} -->
<section class="wp-block-group section" id="compare"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">02</span> The difference</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">What you get instead</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"blocks blocks--3"} -->
<div class="wp-block-group blocks blocks--3"><!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">Instead of a typical agency</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Direct access to the strategist</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>No account managers and no templated deliverables. One system, measured by qualified opportunities rather than traffic reports.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">Instead of a freelancer</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">The definition of the task</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>A freelancer executes a task someone else defined. We start by deciding what to build and why.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">Instead of a national consultant</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Local, on-the-ground context</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Frameworks are easy to find. Knowing how Fort Myers, Naples and Cape Coral buyers choose is harder.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section--tight bg-mark","anchor":"scorecard"} -->
<section class="wp-block-group section--tight bg-mark" id="scorecard"><!-- wp:group {"className":"wrap cta-band"} -->
<div class="wp-block-group wrap cta-band"><!-- wp:group {"className":"stack"} -->
<div class="wp-block-group stack"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Not sure where to start?</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>The 5-minute Digital Growth Scorecard shows whether positioning, your website, search, conversion or follow-up is the bottleneck.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph {"className":"cta-band__action"} -->
<p class="cta-band__action"><a class="btn" href="<?php echo esc_url( home_url( '/growth-scorecard/' ) ); ?>">Take the scorecard <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"final-cta"} -->
<section class="wp-block-group section" id="final-cta"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"final-cta"} -->
<div class="wp-block-group final-cta"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Let’s find your biggest growth opportunity.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">A 30-minute strategy call to see where your growth is stuck — and which of the three to start with.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
