<?php
/**
 * Title: Page: Growth Scorecard
 * Slug: hpv/page-growth-scorecard
 * Categories: hpv-pages
 * Description: 15 questions, 5 minutes: find out whether positioning, website, search or follow-up is your biggest bottleneck.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--inner","anchor":"hero"} -->
<section class="wp-block-group hero hero--inner" id="hero"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:paragraph {"className":"sticker sticker--pink"} -->
<p class="sticker sticker--pink">15 questions · 5 minutes</p>
<!-- /wp:paragraph -->
<!-- wp:group {"className":"hero__text col-8"} -->
<div class="wp-block-group hero__text col-8"><!-- wp:hpv/breadcrumbs /-->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Digital Growth Scorecard · 15 questions · 5 minutes</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display">Where is your growth actually <span class="scribble">stuck</span>?</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">The Digital Growth Scorecard is a 15-question, 5-minute assessment for Florida business owners. It scores five areas — positioning, website, search visibility, conversion and follow-up — and shows your biggest bottleneck.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:hpv/scorecard /-->
