<?php
/**
 * Title: Page: Home
 * Slug: hpv/page-home
 * Categories: hpv-pages
 * Description: I help Southwest Florida businesses turn their website, SEO and marketing into a predictable lead generation system. Fort Myers, Naples, Cape Coral.
 * Post Types: page
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--home","anchor":"hero"} -->
<section class="wp-block-group hero hero--home" id="hero"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:paragraph {"className":"sticker"} -->
<p class="sticker">Straight from Fort Myers</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Digital Growth Strategist · Fort Myers · Naples · Cape Coral</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display"><span class="row">Nice website.</span> <span class="row">Where are</span> <span class="row"><span class="circled">the calls?</span></span></h1>
<!-- /wp:heading -->
<!-- wp:group {"className":"grid hero__grid"} -->
<div class="wp-block-group grid hero__grid"><!-- wp:group {"className":"col-6 stack-lg"} -->
<div class="wp-block-group col-6 stack-lg"><!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Building <mark>digital growth systems</mark> for Florida businesses. Strategic websites, local SEO and follow-up that make Southwest Florida phones ring.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a strategy call <span aria-hidden="true">→</span></a> <span class="hand">30 min. no pitch deck.</span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"hero__area"} -->
<p class="hero__area">Working with owners in Fort Myers, Naples, Cape Coral and across Southwest Florida</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">See the work <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-4 start-9 hero__media"} -->
<div class="wp-block-group col-4 start-9 hero__media"><!-- wp:hpv/photo {"src":"people/aron-hero","ratio":"portrait","alt":"Áron Ritók-Filip, digital growth strategist, in Southwest Florida","note":"Áron, founder of HelloProVision (shoot pending)|","eager":true} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:hpv/ticker {"items":"More calls\nFort Myers\nLess guesswork\nNaples\nOne partner\nCape Coral\nReal numbers\nSouthwest Florida"} /-->

<!-- wp:group {"tagName":"section","className":"proof","anchor":"proof"} -->
<section class="wp-block-group proof" id="proof"><!-- wp:group {"className":"wrap proof__grid"} -->
<div class="wp-block-group wrap proof__grid"><!-- wp:group {"className":"stack"} -->
<div class="wp-block-group stack"><!-- wp:heading {"className":"eyebrow"} -->
<h2 class="wp-block-heading eyebrow">Selected work</h2>
<!-- /wp:heading -->
<!-- wp:list {"className":"proof__names"} -->
<ul class="wp-block-list proof__names"><!-- wp:list-item -->
<li>Factory FM</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Raven Protect</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Tank Empire Budapest</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Mandala</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Kaeri</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>[more clients]</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:group {"className":"proof__metrics"} -->
<div class="wp-block-group proof__metrics"><!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[+X%]</span></span> <span class="stat__ctx">qualified leads for <span class="tbd">[client type]</span></span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[X]</span></span> <span class="stat__ctx">new booked jobs in <span class="tbd">[timeframe]</span></span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[X]×</span></span> <span class="stat__ctx">increase in organic calls</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"problem"} -->
<section class="wp-block-group section" id="problem"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:heading {"className":"h2 col-9"} -->
<h2 class="wp-block-heading h2 col-9">Your website looks professional. So why isn’t it creating opportunities?</h2>
<!-- /wp:heading -->
<!-- wp:group {"className":"col-6 start-2 body stack-sm"} -->
<div class="wp-block-group col-6 start-2 body stack-sm"><!-- wp:paragraph {"className":"lead text-ink"} -->
<p class="lead text-ink">Most Florida businesses we meet don’t have a design problem. They have a <mark class="hl">system problem.</mark></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>The website was built by one company, the SEO is handled by another, the ads by a third — and nobody owns the one number that matters: how many qualified customers reach out each month.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"blocks blocks--3 mt-4"} -->
<div class="wp-block-group blocks blocks--3 mt-4"><!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">Symptom 1</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Traffic without calls.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>People visit, look around and leave. The site answers “who we are” but not “why you, why now.”</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">Symptom 2</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Invisible where it counts.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Competitors show up in the map pack and on page one for the searches your best customers actually make.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">Symptom 3</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Paying for leads you don’t own.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Referral sites and lead marketplaces fill the gap, at a price that grows every season.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"approach"} -->
<section class="wp-block-group section bg-paper" id="approach"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">01</span> Approach</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Growth is a <mark class="hl">system</mark>, not a set of tactics.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Before anything gets built, we find out where your growth is actually stuck. Then every piece — website, search, campaigns, tracking — is designed to work toward the same goal.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process process--4"} -->
<div class="wp-block-group process process--4"><!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">01</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Research</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Your market, your competitors, and how customers in your area search, compare and decide.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">02</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Strategy</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Positioning, offer and priorities. What to do first, and what to ignore.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">03</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Digital System</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Website, local search, campaigns and tracking, built to work together.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">04</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Growth</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Measure qualified opportunities, learn, improve — every month.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"services"} -->
<section class="wp-block-group section" id="services"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">02</span> Services</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">One growth system. Three ways to build it.</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"services"} -->
<div class="wp-block-group services"><!-- wp:group {"tagName":"article","className":"service-card service-card--wide"} -->
<article class="wp-block-group service-card service-card--wide"><!-- wp:group {"className":"service-card__head"} -->
<div class="wp-block-group service-card__head"><!-- wp:paragraph {"className":"service-card__num"} -->
<p class="service-card__num">01</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"service-card__title"} -->
<h3 class="wp-block-heading service-card__title">Digital Growth Consulting</h3>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"stack"} -->
<div class="wp-block-group stack"><!-- wp:paragraph {"className":"service-card__pos"} -->
<p class="service-card__pos">Find the opportunities hiding between your website, your marketing and your customer journey.</p>
<!-- /wp:paragraph -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>A clear growth roadmap based on research, not guesswork</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Priorities ranked by business impact</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>A strategic partner for the decisions in between</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/services/digital-growth-strategy/' ) ); ?>">Explore Digital Growth Strategy <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"service-card"} -->
<article class="wp-block-group service-card"><!-- wp:paragraph {"className":"service-card__num"} -->
<p class="service-card__num">02</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"service-card__title"} -->
<h3 class="wp-block-heading service-card__title">Website Strategy & Development</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"service-card__pos"} -->
<p class="service-card__pos">Not a website. A digital sales system.</p>
<!-- /wp:paragraph -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Built around how your buyers decide</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Fast, search-ready and easy to update</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Designed to turn visits into calls and requests</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/services/website-design-development/' ) ); ?>">Explore Website Design &amp; Development <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"service-card"} -->
<article class="wp-block-group service-card"><!-- wp:paragraph {"className":"service-card__num"} -->
<p class="service-card__num">03</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"service-card__title"} -->
<h3 class="wp-block-heading service-card__title">Local SEO Growth</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"service-card__pos"} -->
<p class="service-card__pos">Be visible when Southwest Florida customers search for what you do.</p>
<!-- /wp:paragraph -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Google Business Profile and map pack visibility</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Service and location pages that rank and convert</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Reviews, reputation and local authority</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/services/local-seo/' ) ); ?>">Explore Local SEO <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></article>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"work"} -->
<section class="wp-block-group section bg-paper" id="work"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">03</span> Work</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Built by my team at HelloProVision.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Websites and digital systems for service, hospitality and local businesses — in Florida and in Europe.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"work"} -->
<div class="wp-block-group work"><!-- wp:group {"tagName":"article","className":"work-item work-item--lg"} -->
<article class="wp-block-group work-item work-item--lg"><!-- wp:hpv/project {"name":"Imperial Kitchens","src":"projects/imperial-kitchens-2","ratio":"wide","tone":3} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/imperial-kitchens/' ) ); ?>">Imperial Kitchens</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat">Kitchen remodeling · Fort Myers</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item work-item--md work-item--offset"} -->
<article class="wp-block-group work-item work-item--md work-item--offset"><!-- wp:hpv/project {"name":"Factory FM","src":"projects/factory-fm-2","ratio":"square","tone":4} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Factory FM</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item work-item--md"} -->
<article class="wp-block-group work-item work-item--md"><!-- wp:hpv/project {"name":"Raven Protect","src":"projects/raven-protect-1","ratio":"square","tone":4} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Raven Protect</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item work-item--lg work-item--offset"} -->
<article class="wp-block-group work-item work-item--lg work-item--offset"><!-- wp:hpv/project {"name":"Tank Empire Budapest","src":"projects/tank-empire-budapest-2","ratio":"wide","tone":6} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Tank Empire Budapest</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat">Budapest, Hungary</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item"} -->
<article class="wp-block-group work-item"><!-- wp:hpv/project {"name":"Mandala","src":"projects/mandala-1","ratio":"land","tone":6} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Mandala</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item"} -->
<article class="wp-block-group work-item"><!-- wp:hpv/project {"name":"Kaeri","src":"projects/kaeri-1","ratio":"land","tone":1} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Kaeri</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item"} -->
<article class="wp-block-group work-item"><!-- wp:hpv/project {"name":"Raven Protect","src":"projects/raven-protect-2","ratio":"land","tone":5} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Raven Protect</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat">Mobile view</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"case-studies"} -->
<section class="wp-block-group section" id="case-studies"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">04</span> Case Studies</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Proof, <mark class="hl">not promises.</mark></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:hpv/case-grid {"layout":"home","count":3,"upcoming":"Factory FM, Tank Empire Budapest"} /-->
<!-- wp:paragraph {"className":"mt-6"} -->
<p class="mt-6"><a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">View all case studies <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-ink on-dark","anchor":"founder"} -->
<section class="wp-block-group section bg-ink on-dark" id="founder"><!-- wp:group {"className":"wrap grid founder"} -->
<div class="wp-block-group wrap grid founder"><!-- wp:group {"className":"col-5"} -->
<div class="wp-block-group col-5"><!-- wp:hpv/photo {"src":"people/aron-desk","ratio":"portrait","alt":"Áron Ritók-Filip working on a website strategy at his desk","note":"Working at the desk · 4:5|Shoot pending","dark":true} /--></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-6 start-7 stack-lg"} -->
<div class="wp-block-group col-6 start-7 stack-lg"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">05</span> Founder</p>
<!-- /wp:paragraph -->
<!-- wp:quote {"className":"quote"} -->
<blockquote class="wp-block-quote quote"><!-- wp:paragraph -->
<p>I don’t just advise businesses. I <mark class="hl">build and grow them</mark> myself.</p>
<!-- /wp:paragraph --></blockquote>
<!-- /wp:quote -->
<!-- wp:group {"className":"body stack-sm"} -->
<div class="wp-block-group body stack-sm"><!-- wp:paragraph -->
<p>I’m Áron Ritók-Filip. Before I advised other companies, I built my own — <span class="tbd">[verified: e.g. founding HelloProVision in (year) and growing (company/project)]</span>. That’s where I learned that growth rarely fails because of one bad tactic. It fails because the pieces don’t connect.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>I bring a European, international perspective to the Florida market, and I work directly with owners — no account managers in between. My team at HelloProVision handles the build; I stay accountable for the result.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/about/' ) ); ?>">More about Áron <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"fit"} -->
<section class="wp-block-group section" id="fit"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Who I work with</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"fit"} -->
<div class="wp-block-group fit"><!-- wp:group {"className":"fit__col fit--yes"} -->
<div class="wp-block-group fit__col fit--yes"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">A good fit if you…</h3>
<!-- /wp:heading -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>run an established business and want predictable growth, not a quick fix</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>sell high-value services where one new client matters</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>are ready to make decisions and invest over 6–12 months</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>want one accountable partner instead of five vendors</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"fit__col fit--no"} -->
<div class="wp-block-group fit__col fit--no"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Probably not a fit if you…</h3>
<!-- /wp:heading -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>need the cheapest website available</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>want guaranteed rankings or overnight results</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>are still validating whether the business works</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"process"} -->
<section class="wp-block-group section section--flush-top" id="process"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">06</span> Process</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">How working together starts.</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"steps"} -->
<div class="wp-block-group steps"><!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"steps__num"} -->
<p class="steps__num">1</p>
<!-- /wp:paragraph -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Strategy call</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"steps__time"} -->
<p class="steps__time">30 minutes</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p>We talk about your business, your goals and what’s not working. You’ll leave with at least one useful insight, whether we work together or not.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"steps__num"} -->
<p class="steps__num">2</p>
<!-- /wp:paragraph -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Growth audit</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"steps__time"} -->
<p class="steps__time">About 2 weeks</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p>I review your website, search visibility, competitors and customer journey, and show you where the biggest opportunities are.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"steps__num"} -->
<p class="steps__num">3</p>
<!-- /wp:paragraph -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Roadmap and proposal</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"steps__time"} -->
<p class="steps__time">After the audit</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p>A clear plan: what to build, in what order, what it costs and how we’ll measure it.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"steps__num"} -->
<p class="steps__num">4</p>
<!-- /wp:paragraph -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Build and grow</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"steps__time"} -->
<p class="steps__time">Ongoing</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p>We execute the system, then improve it monthly based on real results.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section--tight bg-mark","anchor":"scorecard"} -->
<section class="wp-block-group section--tight bg-mark" id="scorecard"><!-- wp:group {"className":"wrap cta-band"} -->
<div class="wp-block-group wrap cta-band"><!-- wp:group {"className":"stack"} -->
<div class="wp-block-group stack"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Not ready for a call? Start with the Digital Growth Scorecard.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>15 questions, 5 minutes. Find out whether positioning, your website, search visibility, conversion or follow-up is holding your growth back.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph {"className":"cta-band__action"} -->
<p class="cta-band__action"><a class="btn" href="<?php echo esc_url( home_url( '/growth-scorecard/' ) ); ?>">Take the 5-minute scorecard <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section","anchor":"insights"} -->
<section class="wp-block-group section" id="insights"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Insights for Florida business owners</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Practical thinking on websites, local search and growth — written for owners, not marketers.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:hpv/insights {"count":3,"fill":true} /--></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"faq"} -->
<section class="wp-block-group section bg-paper" id="faq"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-4"} -->
<div class="wp-block-group col-4"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Questions owners ask</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-8 faq"} -->
<div class="wp-block-group col-8 faq"><!-- wp:details -->
<details class="wp-block-details"><summary>Do you only work with Florida businesses?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">My focus is Southwest Florida — Fort Myers, Naples, Cape Coral and nearby — because local knowledge is part of the value. I also work with select businesses elsewhere in Florida and internationally.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Can you guarantee first-page rankings?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">No one honestly can. What I can promise is a clear strategy, solid execution and transparent reporting on the numbers that matter: calls, requests and booked jobs.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>How long until we see results?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Website and conversion improvements can show impact within weeks. Local SEO typically builds over 3–6 months, depending on competition and your starting point.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Do I need a new website?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Not always. The audit tells us whether to rebuild, improve or leave it alone.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Who actually does the work?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">I lead strategy and stay involved throughout. Design, development and campaigns are delivered by my team at HelloProVision.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>What does it cost?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Every engagement is scoped after the audit. <span class="tbd">[Optional: Projects typically start at $X.]</span></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","className":"section bg-accent","anchor":"final-cta"} -->
<section class="wp-block-group section bg-accent" id="final-cta"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"final-cta"} -->
<div class="wp-block-group final-cta"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Let’s find out where your <mark class="hl">next customers</mark> are coming from.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">A 30-minute strategy call. No pitch deck and no obligation — an honest look at where your growth is stuck and whether I’m the right partner to fix it.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"final-cta__alt"} -->
<p class="final-cta__alt">Prefer email? <a data-track="click_to_email" href="mailto:hello@example.com"><span class="tbd">[hello@domain]</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
