<?php
/**
 * Title: Scorecard band
 * Slug: hpv/scorecard-band
 * Categories: hpv-sections
 * Inserter: no
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section--tight bg-mark","anchor":"scorecard"} -->
<section class="wp-block-group section--tight bg-mark" id="scorecard"><!-- wp:group {"className":"wrap cta-band"} -->
<div class="wp-block-group wrap cta-band"><!-- wp:group {"className":"stack"} -->
<div class="wp-block-group stack"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Not ready for a call? Start with the Digital Growth Scorecard.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>15 questions, 5 minutes. Find out whether positioning, your website, search visibility, conversion or follow-up is holding your growth back.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph {"className":"cta-band__action"} -->
<p class="cta-band__action"><a class="btn" href="<?php echo esc_url( home_url( '/growth-scorecard/' ) ); ?>">Take the 5-minute scorecard <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
