<?php
/**
 * Title: Section: FAQ
 * Slug: hpv/section-faq
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"faq"} -->
<section class="wp-block-group section bg-paper" id="faq"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:group {"className":"col-4"} -->
<div class="wp-block-group col-4"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Questions owners ask</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-8 faq"} -->
<div class="wp-block-group col-8 faq"><!-- wp:details -->
<details class="wp-block-details"><summary>Do you only work with Florida businesses?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">My focus is Southwest Florida — Fort Myers, Naples, Cape Coral and nearby — because local knowledge is part of the value. I also work with select businesses elsewhere in Florida and internationally.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Can you guarantee first-page rankings?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">No one honestly can. What I can promise is a clear strategy, solid execution and transparent reporting on the numbers that matter: calls, requests and booked jobs.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>How long until we see results?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Website and conversion improvements can show impact within weeks. Local SEO typically builds over 3–6 months, depending on competition and your starting point.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Do I need a new website?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Not always. The audit tells us whether to rebuild, improve or leave it alone.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>Who actually does the work?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">I lead strategy and stay involved throughout. Design, development and campaigns are delivered by my team at HelloProVision.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details -->
<details class="wp-block-details"><summary>What does it cost?</summary><!-- wp:paragraph {"className":"faq__a"} -->
<p class="faq__a">Every engagement is scoped after the audit. <span class="tbd">[Optional: Projects typically start at $X.]</span></p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
