<?php
/**
 * Title: Section: Services cards
 * Slug: hpv/section-services
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section","anchor":"services"} -->
<section class="wp-block-group section" id="services"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">02</span> Services</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">One growth system. Three ways to build it.</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"services"} -->
<div class="wp-block-group services"><!-- wp:group {"tagName":"article","className":"service-card service-card--wide"} -->
<article class="wp-block-group service-card service-card--wide"><!-- wp:group {"className":"service-card__head"} -->
<div class="wp-block-group service-card__head"><!-- wp:paragraph {"className":"service-card__num"} -->
<p class="service-card__num">01</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"service-card__title"} -->
<h3 class="wp-block-heading service-card__title">Digital Growth Consulting</h3>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"stack"} -->
<div class="wp-block-group stack"><!-- wp:paragraph {"className":"service-card__pos"} -->
<p class="service-card__pos">Find the opportunities hiding between your website, your marketing and your customer journey.</p>
<!-- /wp:paragraph -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>A clear growth roadmap based on research, not guesswork</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Priorities ranked by business impact</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>A strategic partner for the decisions in between</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/services/digital-growth-strategy/' ) ); ?>">Explore Digital Growth Strategy <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"service-card"} -->
<article class="wp-block-group service-card"><!-- wp:paragraph {"className":"service-card__num"} -->
<p class="service-card__num">02</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"service-card__title"} -->
<h3 class="wp-block-heading service-card__title">Website Strategy & Development</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"service-card__pos"} -->
<p class="service-card__pos">Not a website. A digital sales system.</p>
<!-- /wp:paragraph -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Built around how your buyers decide</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Fast, search-ready and easy to update</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Designed to turn visits into calls and requests</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/services/website-design-development/' ) ); ?>">Explore Website Design &amp; Development <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"service-card"} -->
<article class="wp-block-group service-card"><!-- wp:paragraph {"className":"service-card__num"} -->
<p class="service-card__num">03</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"service-card__title"} -->
<h3 class="wp-block-heading service-card__title">Local SEO Growth</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"service-card__pos"} -->
<p class="service-card__pos">Be visible when Southwest Florida customers search for what you do.</p>
<!-- /wp:paragraph -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Google Business Profile and map pack visibility</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Service and location pages that rank and convert</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Reviews, reputation and local authority</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/services/local-seo/' ) ); ?>">Explore Local SEO <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></article>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
