<?php
/**
 * Title: Section: Proof strip
 * Slug: hpv/section-proof
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"proof","anchor":"proof"} -->
<section class="wp-block-group proof" id="proof"><!-- wp:group {"className":"wrap proof__grid"} -->
<div class="wp-block-group wrap proof__grid"><!-- wp:group {"className":"stack"} -->
<div class="wp-block-group stack"><!-- wp:heading {"className":"eyebrow"} -->
<h2 class="wp-block-heading eyebrow">Selected work</h2>
<!-- /wp:heading -->
<!-- wp:list {"className":"proof__names"} -->
<ul class="wp-block-list proof__names"><!-- wp:list-item -->
<li>Factory FM</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Raven Protect</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Tank Empire Budapest</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Mandala</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Kaeri</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>[more clients]</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:group {"className":"proof__metrics"} -->
<div class="wp-block-group proof__metrics"><!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[+X%]</span></span> <span class="stat__ctx">qualified leads for <span class="tbd">[client type]</span></span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[X]</span></span> <span class="stat__ctx">new booked jobs in <span class="tbd">[timeframe]</span></span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"stat"} -->
<p class="stat"><span class="stat__num"><span class="tbd">[X]×</span></span> <span class="stat__ctx">increase in organic calls</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
