<?php
/**
 * Title: Section: Founder quote (dark)
 * Slug: hpv/section-founder
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section bg-ink on-dark","anchor":"founder"} -->
<section class="wp-block-group section bg-ink on-dark" id="founder"><!-- wp:group {"className":"wrap grid founder"} -->
<div class="wp-block-group wrap grid founder"><!-- wp:group {"className":"col-5"} -->
<div class="wp-block-group col-5"><!-- wp:hpv/photo {"src":"people/aron-desk","ratio":"portrait","alt":"Áron Ritók-Filip working on a website strategy at his desk","note":"Working at the desk · 4:5|Shoot pending","dark":true} /--></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-6 start-7 stack-lg"} -->
<div class="wp-block-group col-6 start-7 stack-lg"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">05</span> Founder</p>
<!-- /wp:paragraph -->
<!-- wp:quote {"className":"quote"} -->
<blockquote class="wp-block-quote quote"><!-- wp:paragraph -->
<p>I don’t just advise businesses. I <mark class="hl">build and grow them</mark> myself.</p>
<!-- /wp:paragraph --></blockquote>
<!-- /wp:quote -->
<!-- wp:group {"className":"body stack-sm"} -->
<div class="wp-block-group body stack-sm"><!-- wp:paragraph -->
<p>I’m Áron Ritók-Filip. Before I advised other companies, I built my own — <span class="tbd">[verified: e.g. founding HelloProVision in (year) and growing (company/project)]</span>. That’s where I learned that growth rarely fails because of one bad tactic. It fails because the pieces don’t connect.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>I bring a European, international perspective to the Florida market, and I work directly with owners — no account managers in between. My team at HelloProVision handles the build; I stay accountable for the result.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/about/' ) ); ?>">More about Áron <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
