<?php
/**
 * Title: Section: Ticker band
 * Slug: hpv/section-ticker
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:hpv/ticker {"items":"More calls\nFort Myers\nLess guesswork\nNaples\nOne partner\nCape Coral\nReal numbers\nSouthwest Florida"} /-->
