<?php
/**
 * Title: Section: Latest insights
 * Slug: hpv/section-insights
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section","anchor":"insights"} -->
<section class="wp-block-group section" id="insights"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Insights for Florida business owners</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Practical thinking on websites, local search and growth — written for owners, not marketers.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:hpv/insights {"count":3,"fill":true} /--></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
