<?php
/**
 * Title: Section: Problem + symptoms
 * Slug: hpv/section-problem
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section","anchor":"problem"} -->
<section class="wp-block-group section" id="problem"><!-- wp:group {"className":"wrap grid"} -->
<div class="wp-block-group wrap grid"><!-- wp:heading {"className":"h2 col-9"} -->
<h2 class="wp-block-heading h2 col-9">Your website looks professional. So why isn’t it creating opportunities?</h2>
<!-- /wp:heading -->
<!-- wp:group {"className":"col-6 start-2 body stack-sm"} -->
<div class="wp-block-group col-6 start-2 body stack-sm"><!-- wp:paragraph {"className":"lead text-ink"} -->
<p class="lead text-ink">Most Florida businesses we meet don’t have a design problem. They have a <mark class="hl">system problem.</mark></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>The website was built by one company, the SEO is handled by another, the ads by a third — and nobody owns the one number that matters: how many qualified customers reach out each month.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"blocks blocks--3 mt-4"} -->
<div class="wp-block-group blocks blocks--3 mt-4"><!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">Symptom 1</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Traffic without calls.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>People visit, look around and leave. The site answers “who we are” but not “why you, why now.”</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">Symptom 2</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Invisible where it counts.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Competitors show up in the map pack and on page one for the searches your best customers actually make.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"block"} -->
<div class="wp-block-group block"><!-- wp:paragraph {"className":"block__num"} -->
<p class="block__num">Symptom 3</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Paying for leads you don’t own.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Referral sites and lead marketplaces fill the gap, at a price that grows every season.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
