<?php
/**
 * Title: Section: Final call to action (pink)
 * Slug: hpv/section-final-cta
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section bg-accent","anchor":"final-cta"} -->
<section class="wp-block-group section bg-accent" id="final-cta"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"final-cta"} -->
<div class="wp-block-group final-cta"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Let’s find out where your <mark class="hl">next customers</mark> are coming from.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">A 30-minute strategy call. No pitch deck and no obligation — an honest look at where your growth is stuck and whether I’m the right partner to fix it.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a Strategy Call <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"final-cta__alt"} -->
<p class="final-cta__alt">Prefer email? <a data-track="click_to_email" href="mailto:hello@example.com"><span class="tbd">[hello@domain]</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
