<?php
/**
 * Title: Section: Hero: Nice website. Where are the calls?
 * Slug: hpv/section-hero
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"hero hero--home","anchor":"hero"} -->
<section class="wp-block-group hero hero--home" id="hero"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:paragraph {"className":"sticker"} -->
<p class="sticker">Straight from Fort Myers</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"eyebrow"} -->
<p class="eyebrow">Digital Growth Strategist · Fort Myers · Naples · Cape Coral</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"display"} -->
<h1 class="wp-block-heading display"><span class="row">Nice website.</span> <span class="row">Where are</span> <span class="row"><span class="circled">the calls?</span></span></h1>
<!-- /wp:heading -->
<!-- wp:group {"className":"grid hero__grid"} -->
<div class="wp-block-group grid hero__grid"><!-- wp:group {"className":"col-6 stack-lg"} -->
<div class="wp-block-group col-6 stack-lg"><!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Building <mark>digital growth systems</mark> for Florida businesses. Strategic websites, local SEO and follow-up that make Southwest Florida phones ring.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"actions"} -->
<p class="actions"><a class="btn" href="<?php echo esc_url( home_url( '/strategy-call/' ) ); ?>">Book a strategy call <span aria-hidden="true">→</span></a> <span class="hand">30 min. no pitch deck.</span></p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"hero__area"} -->
<p class="hero__area">Working with owners in Fort Myers, Naples, Cape Coral and across Southwest Florida</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p><a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">See the work <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"col-4 start-9 hero__media"} -->
<div class="wp-block-group col-4 start-9 hero__media"><!-- wp:hpv/photo {"src":"people/aron-hero","ratio":"portrait","alt":"Áron Ritók-Filip, digital growth strategist, in Southwest Florida","note":"Áron, founder of HelloProVision (shoot pending)|","eager":true} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
