<?php
/**
 * Title: Section: Case studies
 * Slug: hpv/section-case-studies
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section","anchor":"case-studies"} -->
<section class="wp-block-group section" id="case-studies"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">04</span> Case Studies</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Proof, <mark class="hl">not promises.</mark></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:hpv/case-grid {"layout":"home","count":3,"upcoming":"Factory FM, Tank Empire Budapest"} /-->
<!-- wp:paragraph {"className":"mt-6"} -->
<p class="mt-6"><a class="arrow-link" href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">View all case studies <span aria-hidden="true">→</span></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
