<?php
/**
 * Title: Section: Approach (transit line)
 * Slug: hpv/section-approach
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"approach"} -->
<section class="wp-block-group section bg-paper" id="approach"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">01</span> Approach</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Growth is a <mark class="hl">system</mark>, not a set of tactics.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Before anything gets built, we find out where your growth is actually stuck. Then every piece — website, search, campaigns, tracking — is designed to work toward the same goal.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process process--4"} -->
<div class="wp-block-group process process--4"><!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">01</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Research</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Your market, your competitors, and how customers in your area search, compare and decide.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">02</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Strategy</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Positioning, offer and priorities. What to do first, and what to ignore.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">03</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Digital System</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Website, local search, campaigns and tracking, built to work together.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"process__step"} -->
<div class="wp-block-group process__step"><!-- wp:paragraph {"className":"process__num"} -->
<p class="process__num">04</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Growth</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Measure qualified opportunities, learn, improve — every month.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
