<?php
/**
 * Title: Section: How working together starts
 * Slug: hpv/section-process
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section section--flush-top","anchor":"process"} -->
<section class="wp-block-group section section--flush-top" id="process"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">06</span> Process</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">How working together starts.</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"steps"} -->
<div class="wp-block-group steps"><!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"steps__num"} -->
<p class="steps__num">1</p>
<!-- /wp:paragraph -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Strategy call</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"steps__time"} -->
<p class="steps__time">30 minutes</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p>We talk about your business, your goals and what’s not working. You’ll leave with at least one useful insight, whether we work together or not.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"steps__num"} -->
<p class="steps__num">2</p>
<!-- /wp:paragraph -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Growth audit</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"steps__time"} -->
<p class="steps__time">About 2 weeks</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p>I review your website, search visibility, competitors and customer journey, and show you where the biggest opportunities are.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"steps__num"} -->
<p class="steps__num">3</p>
<!-- /wp:paragraph -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Roadmap and proposal</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"steps__time"} -->
<p class="steps__time">After the audit</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p>A clear plan: what to build, in what order, what it costs and how we’ll measure it.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"steps__num"} -->
<p class="steps__num">4</p>
<!-- /wp:paragraph -->
<!-- wp:group -->
<div class="wp-block-group"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Build and grow</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"steps__time"} -->
<p class="steps__time">Ongoing</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:paragraph -->
<p>We execute the system, then improve it monthly based on real results.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
