<?php
/**
 * Title: Section: Work wall
 * Slug: hpv/section-work
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section bg-paper","anchor":"work"} -->
<section class="wp-block-group section bg-paper" id="work"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:paragraph {"className":"label"} -->
<p class="label"><span class="label__num">03</span> Work</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Built by my team at HelloProVision.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"lead"} -->
<p class="lead">Websites and digital systems for service, hospitality and local businesses — in Florida and in Europe.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"work"} -->
<div class="wp-block-group work"><!-- wp:group {"tagName":"article","className":"work-item work-item--lg"} -->
<article class="wp-block-group work-item work-item--lg"><!-- wp:hpv/project {"name":"Imperial Kitchens","src":"projects/imperial-kitchens-2","ratio":"wide","tone":3} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/imperial-kitchens/' ) ); ?>">Imperial Kitchens</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat">Kitchen remodeling · Fort Myers</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item work-item--md work-item--offset"} -->
<article class="wp-block-group work-item work-item--md work-item--offset"><!-- wp:hpv/project {"name":"Factory FM","src":"projects/factory-fm-2","ratio":"square","tone":4} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Factory FM</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item work-item--md"} -->
<article class="wp-block-group work-item work-item--md"><!-- wp:hpv/project {"name":"Raven Protect","src":"projects/raven-protect-1","ratio":"square","tone":4} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Raven Protect</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item work-item--lg work-item--offset"} -->
<article class="wp-block-group work-item work-item--lg work-item--offset"><!-- wp:hpv/project {"name":"Tank Empire Budapest","src":"projects/tank-empire-budapest-2","ratio":"wide","tone":6} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Tank Empire Budapest</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat">Budapest, Hungary</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item"} -->
<article class="wp-block-group work-item"><!-- wp:hpv/project {"name":"Mandala","src":"projects/mandala-1","ratio":"land","tone":6} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Mandala</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item"} -->
<article class="wp-block-group work-item"><!-- wp:hpv/project {"name":"Kaeri","src":"projects/kaeri-1","ratio":"land","tone":1} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Kaeri</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat"><span class="tbd">[industry]</span></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group -->
<!-- wp:group {"tagName":"article","className":"work-item"} -->
<article class="wp-block-group work-item"><!-- wp:hpv/project {"name":"Raven Protect","src":"projects/raven-protect-2","ratio":"land","tone":5} /-->
<!-- wp:group {"className":"work-item__meta"} -->
<div class="wp-block-group work-item__meta"><!-- wp:heading {"level":3,"className":"work-item__name"} -->
<h3 class="wp-block-heading work-item__name"><a href="<?php echo esc_url( home_url( '/case-studies/' ) ); ?>">Raven Protect</a></h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"work-item__cat"} -->
<p class="work-item__cat">Mobile view</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></article>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
