<?php
/**
 * Title: Section: Who I work with
 * Slug: hpv/section-fit
 * Categories: hpv-sections
 *
 * Generated by tools/build_theme.py from the HTML prototype. Edit the prototype and rebuild.
 *
 * @package HelloProVision
 */

defined( 'ABSPATH' ) || exit;
?>
<!-- wp:group {"tagName":"section","className":"section","anchor":"fit"} -->
<section class="wp-block-group section" id="fit"><!-- wp:group {"className":"wrap"} -->
<div class="wp-block-group wrap"><!-- wp:group {"className":"section-head"} -->
<div class="wp-block-group section-head"><!-- wp:heading {"className":"h2"} -->
<h2 class="wp-block-heading h2">Who I work with</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"fit"} -->
<div class="wp-block-group fit"><!-- wp:group {"className":"fit__col fit--yes"} -->
<div class="wp-block-group fit__col fit--yes"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">A good fit if you…</h3>
<!-- /wp:heading -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>run an established business and want predictable growth, not a quick fix</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>sell high-value services where one new client matters</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>are ready to make decisions and invest over 6–12 months</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>want one accountable partner instead of five vendors</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group -->
<!-- wp:group {"className":"fit__col fit--no"} -->
<div class="wp-block-group fit__col fit--no"><!-- wp:heading {"level":3,"className":"h3"} -->
<h3 class="wp-block-heading h3">Probably not a fit if you…</h3>
<!-- /wp:heading -->
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>need the cheapest website available</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>want guaranteed rankings or overnight results</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>are still validating whether the business works</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
